name: Build & Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      platform:
        description: "选择要构建的平台"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - windows
          - macos
          - linux

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    if: github.event_name == 'push' || inputs.platform == 'linux' || inputs.platform == 'all'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --verbose
      - name: Prepare Asset
        run: |
          cp target/release/yewpb yewpb-linux-amd64
      - uses: actions/upload-artifact@v4
        with:
          name: yewpb-linux-amd64
          path: yewpb-linux-amd64

  build-windows:
    name: Build Windows
    if: github.event_name == 'push' || inputs.platform == 'windows' || inputs.platform == 'all'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --verbose
      - name: Prepare Asset
        shell: bash
        run: |
          cp target/release/yewpb.exe yewpb-windows-amd64.exe
      - uses: actions/upload-artifact@v4
        with:
          name: yewpb-windows-amd64.exe
          path: yewpb-windows-amd64.exe

  build-macos:
    name: Build macOS
    if: github.event_name == 'push' || inputs.platform == 'macos' || inputs.platform == 'all'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --verbose
      - name: Prepare Asset
        run: |
          cp target/release/yewpb yewpb-macos-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: yewpb-macos-arm64
          path: yewpb-macos-arm64

  create-release:
    name: Create Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      
      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          generate_release_notes: true
